<?php
include('head.php');
?>
<?php
include('header.php');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>about-Hamronews</title>
    <link rel="stylesheet" href="style.css">

    <style>
      
    </style>
</head>
<body>
<div class="frame">

<h1><b>Our Introduction</b></h1> 
<h3>
This website is generated by Hamronews.com. This website is one
 of the unique website is which is news and new update published at 
 this time.Our website was developed in 2022 or 2079 at middle years. 
 When all visitor visit our website then get new update or most 
 important information for his useful purpose. Whose visitor read 
 and see this news portal then they are felling of some new activate.
 </h3><br>
<h1><b>Our purpose</b> </h1><h3>
Now days almost people get information by online social media but all social 
media are not published real information own his customer. So that we can give 
up real and fast information to people. The mainly our mission is similar to
other news organization for inform all people which new update in the world and country.  
		The many Organization in the online social media they to do make easily
         work to every people from give online information. Some of the social media
          cannot produce real information on target or focusing on that subject. We
           can published content which are inform able for every and similar field. 
        </h3> <br>
<h1><b> Our Office</b></h1> <br>
<h3>
1.	Head office Kathmandu Putalishadak <br>
2.	Branch office Nepalgunj Banke <br>
3.	Branch office Surkhet <br>
4.	Branch office Butwal Rupandehi <br>
5.	Branch office Biratnaga
</h3>
</div>
    
</body>
</html>
<?php
include("footer.php");
?>